### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by davidlj95** [jWinterDay/cool_linter#11]
Hi !

I was about to use the package for a project, however, couldn't install it because depends on `analyzer: ^1.7.0` and we're using `analyzer: ^2.6.0`.

After checking [`pubspec.yaml`](https://github.com/jWinterDay/cool_linter/blob/98255732e06144c3a722c6cc0124b511d505b69e/pubspec.yaml) seems that the package is ready to support `analyzer: ^2.8.0` (since https://github.com/jWinterDay/cool_linter/commit/2940fb9a6702ce9a73e9dd0d5ebfd0425c591bb6)

But since no new package release (since (https://github.com/jWinterDay/cool_linter/commit/9ebe662aa2096b462196023762cdca4e9ca1e5b8 I assume), can not leverage that change.

Could we publish a new version of the package, to be able to use `analyzer` `^2` versions?

Thanks !

**Comment by jWinterDay** [comment]
@davidlj95 hello. I'v just published it but I didn't tested it and now I don't have a time to do it. Please give me feedback if it will not work correctly

**Comment by davidlj95** [comment]
so fast ! I'll test it and let you know. thanks a lot 👍

**Comment by davidlj95** [comment]
All seems to be working properly (setup `cool_linter` with a RegExp rule) . Thanks again 👍
