### ISSUE TITLE
Incompatible with freezed v2

### ISSUE THREAD

**Issue by bartekpacia** [jWinterDay/cool_linter#13]
```
$ flutter pub get
Because cool_linter >=2.4.0 depends on freezed_annotation ^1.1.0 and companion depends on freezed_annotation ^2.0.3, cool_linter >=2.4.0 is forbidden.
So, because companion depends on cool_linter ^2.4.0, version solving failed.
Running "flutter pub get" in mobile...
pub get failed (1; So, because companion depends on cool_linter ^2.4.0, version solving failed.)
```

**Comment by jWinterDay** [comment]
hello @bartekpacia
thanks for your feedback

you can solve this problem with two ways:

1) override your dependencies in pubspec.yaml file like
dependency_overrides:
  freezed_annotation: ^1.1.0

2) I have recently made fix, but haven't checked it
you can help me if you check it
try to change cool_linter dependency in you pubspec.yaml to

cool_linter:
  git: https://github.com/jWinterDay/cool_linter.git
  ref: feature/v2.5.0

if the second way will help you I will merge it to master branch and publish to pub.dev

thanks!

**Comment by bartekpacia** [comment]
Hi @jWinterDay! Thanks for fast response.

I went with way 2 and no dependency conflicts arose, `fluter pub get` worked just fine. However, `cool_linter` doesn't seem to be working at all. It does not highlight code that it was previously highlighting.

**Comment by jWinterDay** [comment]
@bartekpacia ok, thanks. I will check it

**Comment by jWinterDay** [comment]
@bartekpacia I have just tested it.
for my VsCode it highlights correctly
![Screenshot 2022-05-12 at 15 47 37](https://user-images.githubusercontent.com/11569455/168078111-c26f0d64-f198-4db3-8591-cb976d52e723.png)
y

Did you restart analyse server? You can try restart your IDE or kill dart processes - killall dart

**Comment by bartekpacia** [comment]
@jWinterDay then it must've been something with my local install.

Please feel free to release `v2.5.0` :) And also big thanks for this package!

**Comment by jWinterDay** [comment]
@bartekpacia thanks, I will release it :)
